### ISSUE TITLE
Please add me to the MarketSquare

### ISSUE THREAD

**Issue by fonzai** [MarketSquare/MarketSquare#11]
Thank you! :)

**Comment by emanlove** [comment]
@fonzai An invitation to join has been sent to your GitHub account email. If there are issues just let me know and I can try to resolve.

Welcome to MarketSquare!

**Comment by fonzai** [comment]
@emanlove Sorry, I was on holidays and forgot to accept the invite in time (it's expired now). Could you please send it again. Sorry for the extra hassle 😔.

**Comment by emanlove** [comment]
Timo, sorry I missed this note. I have resent. If you have any issue just let me know. Torilla Tavataan!

**Comment by fonzai** [comment]
@emanlove Thanks, got in now! 👍

**Comment by emanlove** [comment]
Great to hear! Welcome to MarketSquare!
