### ISSUE TITLE
Please add me to the MarketSquare

### ISSUE THREAD

**Issue by Snooz82** [MarketSquare/MarketSquare#14]
Hi Ed,

Can you please add me and create a new Repo `robotframework-browser.org`
and make me admin.

Thanks!

**Comment by emanlove** [comment]
René you should be able to create a new repository within MarketSquare as a member. With regards to certain higher level functionality you may need a MarketSquare admin to add/permission it. But creation is open to everyone. See "New Repository" under https://marketsquare.github.io/.

**Comment by emanlove** [comment]
Sorry about that.  An invitation to join has been sent to your GitHub account email. If there are issues just let me know and I can try to resolve.

Welcome to MarketSquare!
