### ISSUE TITLE
Please assist with transfer repo with Github Actions

### ISSUE THREAD

**Issue by emanlove** [MarketSquare/MarketSquare#18]
@Hi-Fi   Juho could you assist @mnojek and @bhirsz with transfering their repository [bhirsz/robotframework-robocop](https://github.com/bhirsz/robotframework-robocop) which has some actions if you get a chance? I need to familiarize myself with Actions better so this might be a good opportunity to learn from you. Kiitos!

**Comment by Hi-Fi** [comment]
What kind of help is needed? If ownership of the repo is changed to Marketsquare, also secrets used by actions are moved (if there's any). 

GHA itself doesn't need any special things in normal cases.

**Comment by emanlove** [comment]
Thanks for the clarification Juho! I wasn't sure from your move of the java seleniumlibrary if you had to do anything special in that regard.

**Comment by bhirsz** [comment]
We successfully migrated our repository to MarketSquare (now at https://github.com/MarketSquare/robotframework-robocop). It looks like our github actions were copied over without any issues.
Thanks @emanlove @Hi-Fi

**Comment by emanlove** [comment]
Great and Welcome to MarketSquare!
