### ISSUE TITLE
Please add me to the MarketSquare

### ISSUE THREAD

**Issue by jg8481** [MarketSquare/MarketSquare#2]
Thank you Ed!

**Comment by emanlove** [comment]
An invitation has been sent to your GitHub account email. Please follow the instructions provide which will complete your joining the MarketPlace.

Torilla Tavataan!

**Comment by jg8481** [comment]
@emanlove I'm wondering could we also use MarketSquare for a place to post "Help Wanted" messages openly to the community?

**Comment by emanlove** [comment]
Do you mean, for example, as a developer on the [marketsquare/robotframework-primefaces](https://github.com/MarketSquare/robotframework-primefaces) project I am looking for others to help contribute to this particular project? Or do you mean posting "looking for job" and/or "have available positions for hire" type advertisements? Or something else?

Also by what means and to where would these postings go?

**Comment by jg8481** [comment]
Hi Ed. I will get in touch with you on Slack about this.
