### ISSUE TITLE
run RF case multiple times with $ robot {testcasename} . . . . . . does not work as expected

### ISSUE THREAD

**Issue by xuyang61** [MarketSquare/MarketSquare#24]
$ robot {testcasename} . . . . . .

suppose to run a test case multiple times depends on the dots put after test case name. I tried it, it actually run the test case specific, then it run all the test cases under the same directory with the test case. Is this a known error for current RF release? When it will be corrected? how shall I run a single cases (or cases under same keywords) multiple times?

**Comment by emanlove** [comment]
@xuyang61 The Slack channel, as well as the other community channels, are best for asking questions about how to use Robot Framework. The marketsquare/MarketSquare issues are best for questions about MarketSquare, our community GitHub organization for sharing robot framework related repositories.

In regards to your question, I am not aware of that execution option to run a test case multiple times by the number of dots. The form I am aware of [is outlined here](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#starting-test-execution). That is the `robot` command followed by a space. Then any arguments then a space ending with either the file or directory to execute. So a command ending with a space and then a dot would execute all robot test suite files found in the present working directory. You might check to see if there is a space between you testcase name and the dots. If so I suspect this s how the executor is interpreting your command. And again I'm not aware of the option to run a testcasename multiple times as you noted above.

**Comment by xuyang61** [comment]
@emanlove Thanks for your answer. I will move to slack for future.

**Comment by emanlove** [comment]
No problem. Have a good day!
