### ISSUE TITLE
Please add me to the MarketSquare

### ISSUE THREAD

**Issue by datakurre** [MarketSquare/MarketSquare#25]
For starters, I'd like to give ownership of https://github.com/datakurre/robotframework-seleniumscreenshots to market square in case that I am unable to fix possible issues. Could be that it is already in "maintenance mode" due to robotframework-browser, but that just one more reason to archive it here :)

Do you already have collective user at PyPI?

**Comment by emanlove** [comment]
We do. It is `marketsquare` - https://pypi.org/user/marketsquare/. And we would be happy to host seleniumscreenshots.

**Comment by emanlove** [comment]
@datakurre An invitation to join has been sent to your GitHub account email. If there are issues just let me know and I can try to resolve.

Welcome to MarketSquare!

**Comment by datakurre** [comment]
@emanlove Thanks a lot! And another thank you for introducing this "collective" practice for Robot Framework community!
