### ISSUE TITLE
Request for joining market square

### ISSUE THREAD

**Issue by kstine** [MarketSquare/MarketSquare#30]
Looking to create a repo for work on the "RF-8" style guide.

**Comment by emanlove** [comment]
@kstine Was this a request to join marketsquare or to create a repo? If it was to create a repo you have permissions to do that yourself. If if you like I could but I see it best as you have the idea and the leadership for the style guide.

**Comment by kstine** [comment]
Yes- I intend to make a repo as part of my robocon presentation. Trying to get my ducks in a row. ;}
