### ISSUE TITLE
Maintainer of the webdrivermanager package request

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [MarketSquare/MarketSquare#39]
Hi guys I would like to become a maintainer of the package webdrivermanager for python created by you.
I noticed that it has been a bit forgotten since there are PRs and Issues not responded/fixed so I would like to give an extra hand with it.

**Comment by emanlove** [comment]
@DEADSEC-SECURITY what would you suggest in regards to the changes to selenium around drivers?

**Comment by DEADSEC-SECURITY** [comment]
For that package in specific, auto version checking and a check if already installed before downloading and installing.

**Comment by emanlove** [comment]
I was meaning in regards to the [selenium manager](https://www.selenium.dev/blog/2022/introducing-selenium-manager/).

**Comment by DEADSEC-SECURITY** [comment]
That package I never used.

**Comment by emanlove** [comment]
Thanks for the offer but at this time we have a team that will re look at this. Thank you for bringing this up and bringing it to our attention.

I'll add there are a few projects within the Robot Framework ecosystem that if you are interested in getting involved I suggest you reaching out to the individual projects. I good place to get started is https://robotframework.org/
