### ISSUE TITLE
Please add me to the MarketSquare

### ISSUE THREAD

**Issue by Dighkh** [MarketSquare/MarketSquare#43]
Hello MarketSquare Community,

I have developed a JavaScript extension for the browser library that helps capture network traffic while tests are running. 

By integrating this extension, users can monitor network activity in real-time.

Thank you for considering my proposal.

Best regards,
Odai Alkhodary

**Comment by emanlove** [comment]
@Dighkh, An invitation to join has been sent to your GitHub account email. If there are issues just let me know and I can try to resolve.

Welcome to MarketSquare!
